# Homework 1 - Numpy Arrays

### Readings from PPNM:
Chapter    2.7:  Introducing Arrays

Chapter     14:  Basics of Matrices and Linear Algebra

Chapter 16.4.2:  Calculating Betas Using Inverse 


## Our Assignment Goals
Work through these examples of basic vector and matrix operations, then you will be asked to provide 3 things:
- Calculate the betas for a regression of two X variables onto a Y vector using matrix formulation -  using module "numpy" (3 betas - 1 beta for the intercept, and 2 betas for the two X predictor variables)
- Write out the regression equation for predicted Y values using the betas.  Leave Y, X and Epsilon as symbols, and insert your estimated beta values:   <br> $$\hat{Y}=\hat{\beta_0}+\hat{\beta_1}*X_1+\hat{\beta_2}*X_2+\varepsilon$$<br>

- Lastly, show hand calculations that a defined matrix $A$ and it's inverse $A^{-1}$ give back the identity matrix

## Part I:  Examples

### Creating Vectors and Matrices

In [7]:
# Import numpy
import numpy as np

# An array, no orientation
v2 = np.array([2,5,4,7])

# Creating a 4 by 1 column vector; The "shape" property gives the dimensions of the matrix  
v3 = np.array([ [2],[5],[4],[7] ])
print(v3)
print("")
print(v3.shape)
print("")

# Creating a 1 by 4 row vector
v4 = np.array([ [2,5,4,7] ]) 
print(v4)
print("")
print(v4.shape)
print("")

# Creating a 2x3 matrix
v5=np.array([[2,4,6],
             [8,10,12]])
print(v5)
print("")
print(v5.shape)
print("")

# Creating a 3x2 matrix
v6=np.array([[2,4], [6,8], 
             [10,12]])
print(v6)
print("")
print(v6.shape)


[[2]
 [5]
 [4]
 [7]]

(4, 1)

[[2 5 4 7]]

(1, 4)

[[ 2  4  6]
 [ 8 10 12]]

(2, 3)

[[ 2  4]
 [ 6  8]
 [10 12]]

(3, 2)


### Transpose

In [8]:
# Create a random 2x5 matrix
A = np.random.randn(2,5)
print(A)
print("")

# Two ways to transpose
At1 = A.T
print(At1)
print("")

At2 = np.transpose(A)
print(At2)

[[-2.14249844 -0.56601305  0.37060285 -0.83715481  2.18737322]
 [ 0.25517423  0.87795555  0.81233779 -1.9634466  -0.56179902]]

[[-2.14249844  0.25517423]
 [-0.56601305  0.87795555]
 [ 0.37060285  0.81233779]
 [-0.83715481 -1.9634466 ]
 [ 2.18737322 -0.56179902]]

[[-2.14249844  0.25517423]
 [-0.56601305  0.87795555]
 [ 0.37060285  0.81233779]
 [-0.83715481 -1.9634466 ]
 [ 2.18737322 -0.56179902]]


### Vector and Matrix Multiplication

In [9]:
# Create two vectors v1 and v2
v1 = np.array([[2,5,4,7]])
v2 = np.array([[4,1,0,2]])

# Multiple the two vectors (dot product); this also works with matrices with
# same inner index - in this case (1, 4) times (4, 1)
dp = np.dot(v1,v2.T)
print(dp)
print("")

# Create a 2x3 and a 3x2 matrix then multiply them and should produce
# a 2x2 matrix
v3=np.array([[2,4,6],
             [8,10,12]])
print(v3)
print("")
print(v3.shape)
print("")

# Creating a 3x2 matrix
v4=np.array([[2,4], [6,8], 
             [10,12]])
print("")
print(v4.shape)
print("")

v5=np.dot(v3, v4)
print(v5)
print("")
print(v5.shape)
print("")

# Another way to multiply using "at" symbol - @
v6=v3@v4
print(v6)
print("")
print(v6.shape)


[[27]]

[[ 2  4  6]
 [ 8 10 12]]

(2, 3)


(3, 2)

[[ 88 112]
 [196 256]]

(2, 2)

[[ 88 112]
 [196 256]]

(2, 2)


### Matrix Inverse

In [10]:
# numpy uses the "np.linalg.inv()" function to calculate the 
# inverse of a square matrix

v3=np.array([[2,4,6],
             [8,10,12]])
print(v3)
print("")
print(v3.shape)
print("")

# Creating a 3x2 matrix
v4=np.array([[2,4], [6,8], 
             [10,12]])
print("")
print(v4.shape)
print("")

v5 = v3@v4
print(v5)
print("")

v5_inv=np.linalg.inv(v5)
print("Inverse:")
print("")
print(v5_inv)
print("")
print(v5_inv.shape)

[[ 2  4  6]
 [ 8 10 12]]

(2, 3)


(3, 2)

[[ 88 112]
 [196 256]]

Inverse:

[[ 0.44444444 -0.19444444]
 [-0.34027778  0.15277778]]

(2, 2)


## Part II:  Calculating the Beta Coefficients for a Linear Regression and Writing out the Prediction Equation

### First we create a response vector Y and a predictor matrix X for the assignment

In [11]:
# Import numpy module
import numpy as np

# Consider the Y vector to be a variable labeled "Missed Days at Work";
# there are 12 rows (objects)

Y=np.array([1,0,1,4,3,2,5,6,9,13,15,16])
print(Y)

[ 1  0  1  4  3  2  5  6  9 13 15 16]


In [12]:
# Consider column 2 of X to be a variable labeled "Attitude Toward Work" - a 1 to 13 point
# rating scale where 1 is extremely favorable and 13 is extremely unfavorable;
# and consider column 3 of X to be a variable labeled "Years in Present Position";
# X has 12 rows and 3 columns;  the first column is all 1's

X=np.array([[1,1,1],
           [1,2,1],
           [1,2,2],
           [1,3,2],
           [1,5,4],
           [1,5,6],
           [1,6,5],
           [1,7,4],
           [1,10,8],
           [1,11,7],
           [1,11,9],
           [1,12,10]])
print(X)

[[ 1  1  1]
 [ 1  2  1]
 [ 1  2  2]
 [ 1  3  2]
 [ 1  5  4]
 [ 1  5  6]
 [ 1  6  5]
 [ 1  7  4]
 [ 1 10  8]
 [ 1 11  7]
 [ 1 11  9]
 [ 1 12 10]]


In [13]:
# Dimensions of Y: a 12 by 1 vector
Y.shape

(12,)

In [14]:
# Dimensions of X: a 12 by 3 matrix
X.shape

(12, 3)

## Calculating Linear Regression Betas
### Using the following matrix formulation for the betas:
$$ \hat{\beta }= (X^{T}*X)^{-1}*X^{T}*Y$$


In [21]:
from numpy.linalg import inv
X_tran= X.T
print("Y matrix")
print(Y)
print("X matrix")
print(X)
beta_values = np.dot(np.dot((inv(np.dot(X_tran,X))),X_tran),Y)
print("beta values")
beta_values

Y matrix
[ 1  0  1  4  3  2  5  6  9 13 15 16]
X matrix
[[ 1  1  1]
 [ 1  2  1]
 [ 1  2  2]
 [ 1  3  2]
 [ 1  5  4]
 [ 1  5  6]
 [ 1  6  5]
 [ 1  7  4]
 [ 1 10  8]
 [ 1 11  7]
 [ 1 11  9]
 [ 1 12 10]]
beta values


array([-2.2630379 ,  1.54972927, -0.2385295 ])

- __Using the Y vector and the X matrix defined above, calculate the betas using the matrix operations:  transpose, matrix multiplication,  and the inverse__.  Section 16.4.1 of __PPNM__ gives a good example of using the numpy module to calculate the betas using the matrix formulation.  Use these betas to write out the prediction equation for Y predict, leaving the Y, X, and Epsilon as symbolic variables

## Part III:  Calculations Showing that $A$ and $A^{-1}$ Multiplied Give the Identity Matrix

In class we used the following matrix A and it's inverse as example in class.   Below are the numpy commands that would multiply these matrices together to get back the identity matrix.   __Your task is to write out the multiplication of these two matrices by hand (I suggest pencil and paper) - STEP BY STEP - SHOWING ALL OF THE CALCULATIONS - the additions and the multiplications of each dot product before reducing.  You will not get credit for the hand calculations if you do not show all of your work.__   

In [28]:
# Define A matrix
A=np.array([[2,3],
             [-1, 4]])
print(A)
print("")
print(A.shape)
print("")

# Create inverse of A matrix  
A_inv=np.array([[4/11,-3/11], 
              [1/11,2/11]])
print(A_inv)
print("")
print(A_inv.shape)
print("")

# Multiply the two matrices to get back the identity matrix 
ident_A = A @ A_inv
print(ident_A)
print("")


[[ 2  3]
 [-1  4]]

(2, 2)

[[ 0.36363636 -0.27272727]
 [ 0.09090909  0.18181818]]

(2, 2)

[[1.00000000e+00 5.55111512e-17]
 [0.00000000e+00 1.00000000e+00]]



In [36]:
import numpy as np
A = np.array([[2, 3],[-1, 4]])

A_inv = np.linalg.inv(A)

new = np.dot(A,A_inv)

print(new) 

[[1.00000000e+00 5.55111512e-17]
 [0.00000000e+00 1.00000000e+00]]


### You will need to submit the following to the upload field for the assignment:

- Submit your .ipynb notebook - make sure to run the notebook in it's entirety and do not hide (collapse) any output cells!   
- Submit a .pdf or .doc file showing your results of your ipynb notebook calculations 
- And lastly submit your hand calculations 
<br><br>
Feel free to compare your python results with the R results before submitting your ipython notebook and .pdf/.doc file.